-- Check-in question bank migration.
-- Run in Supabase SQL Editor once before using the bank-style check-in admin.
--
-- The old app used q_date as the daily schedule key, usually with values like
-- 2026-06-22. The new app uses the same table as a question bank and stores
-- generated keys such as pool:<uuid>, so q_date must be text.

create table if not exists public.checkin_questions (
  q_date text primary key,
  body jsonb not null default '{}'::jsonb
);

alter table public.checkin_questions
  alter column q_date type text using q_date::text;

create table if not exists public.checkin_responses (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);
